name: labyrinth
version: '0.1.0.0'
category: Game
author: Leon Coto
maintainer: leoncoto@gmail.com
copyright: Leon Coto
license: BSD3
github: grancalavera/labyrinth
extra-source-files:
- README.md
library:
  source-dirs:
  - lib
  ghc-options:
  - -Wall
  exposed-modules:
  - Labyrinth
  - Labyrinth.GameDescription
  - Labyrinth.Direction
  - Labyrinth.Game
  - Labyrinth.Gate
  - Labyrinth.Goal
  - Labyrinth.Players
  - Labyrinth.Tile
  - Labyrinth.UI
  - Labyrinth.UI.Game
  - Labyrinth.UI.Players
  dependencies:
  - base >=4.7 && <5
  - brick
  - containers
  - linear
  - microlens
  - microlens-th
  - random
  - vty
  - array
  - mtl
  - text
executables:
  labyrinth:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - base
    - labyrinth
tests:
  labyrinth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - labyrinth
    - hspec
    - hspec-discover
    - microlens
    - QuickCheck
