name: labyrinth
version: "0.1.0.0"
category: Game
author: Leon Coto
maintainer: leoncoto@gmail.com
copyright: Leon Coto
license: BSD3
github: grancalavera/labyrinth
extra-source-files:
  - README.md

dependencies:
  - base >=4.7 && <5
  - brick
  - containers
  - either
  - linear
  - lens
  - MonadRandom
  - mtl
  - random
  - text
  - validation
  - vty

library:
  source-dirs:
    - lib
  default-extensions:
    - DuplicateRecordFields
    - NamedFieldPuns
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - TemplateHaskell
    - LambdaCase
    - TupleSections
    - DeriveFunctor
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
  exposed-modules:
    - Labyrinth.Game
    - Labyrinth.Game.Configuration
    - Labyrinth.Game.Position
    - Labyrinth.Game.Player
    - Labyrinth.Game.Treasure
    - Labyrinth.Game.Cell
    - Labyrinth.Game.Direction
    - Labyrinth.Game.Class
    - Labyrinth.Game.Builder
    - Labyrinth.UI
    - Labyrinth.UI.Modal
    - Labyrinth.UI.Debug
    - Labyrinth.UI.Screen.Setup
    - Labyrinth.UI.Screen.Game
    - Labyrinth.UI.Widget
    - Labyrinth.Store
    - Labyrinth.Store.Event.Modal
    - Labyrinth.Store.Event.Setup
    - Data.List.Extended

executables:
  labyrinth:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    default-extensions:
      - DuplicateRecordFields
      - NamedFieldPuns
      - OverloadedStrings
      - RankNTypes
      - RecordWildCards
      - TemplateHaskell
      - LambdaCase
      - TupleSections
    dependencies:
      - labyrinth

tests:
  labyrinth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - DuplicateRecordFields
      - NamedFieldPuns
      - OverloadedStrings
      - RankNTypes
      - RecordWildCards
      - TemplateHaskell
      - LambdaCase
      - TupleSections
    dependencies:
      - labyrinth
      - hspec
      - hspec-discover
