name: labyrinth
version: '0.1.0.0'
category: Game
author: Leon Coto
maintainer: leoncoto@gmail.com
copyright: Leon Coto
license: BSD3
github: grancalavera/labyrinth
extra-source-files:
- README.md
library:
  source-dirs:
  - lib
  ghc-options:
  - -Wall
  exposed-modules:
  - Labyrinth
  - Labyrinth.Direction
  - Labyrinth.Game
  - Labyrinth.Gate
  - Labyrinth.Goal
  - Labyrinth.Players
  - Labyrinth.Tile
  - Data.List.Extended
  dependencies:
  - base >=4.7 && <5
  - containers
  - linear
  - microlens
  - microlens-th
  - random
  - array
  - text
  - mtl
executables:
  labyrinth:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - base
    - brick
    - containers
    - labyrinth
    - linear
    - microlens
    - microlens-th
    - text
    - vty
tests:
  labyrinth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - labyrinth
    - hspec
    - hspec-discover
    - microlens
    - QuickCheck
