name: labyrinth
version: "0.1.0.0"
category: Game
author: Leon Coto
maintainer: leoncoto@gmail.com
copyright: Leon Coto
license: BSD3
github: grancalavera/labyrinth
extra-source-files:
  - README.md

library:
  source-dirs:
    - lib
  default-extensions:
    - DuplicateRecordFields
    - NamedFieldPuns
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - TemplateHaskell
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
  exposed-modules:
    - Labyrinth
    - Labyrinth.Game
    - Labyrinth.Game.Direction
    - Labyrinth.Game.Gate
    - Labyrinth.Game.Players
    - Labyrinth.Game.Tile
    - Labyrinth.Game.Treasure
    - Labyrinth.UI
    - Labyrinth.UI.Screen.Registration
    - Labyrinth.UI.Screen.Splash
    - Labyrinth.Store
    - Labyrinth.Store.Event.Splash
    - Labyrinth.Store.Event.Registration
    - Data.List.Extended
  dependencies:
    - base >=4.7 && <5
    - array
    - brick
    - containers
    - linear
    - microlens
    - microlens-th
    - mtl
    - random
    - text
    - vty

executables:
  labyrinth:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    default-extensions:
      - DuplicateRecordFields
      - NamedFieldPuns
      - OverloadedStrings
      - RankNTypes
      - RecordWildCards
      - TemplateHaskell
    dependencies:
      - base
      - brick
      - containers
      - labyrinth
      - linear
      - microlens
      - microlens-th
      - text
      - vty

tests:
  labyrinth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - DuplicateRecordFields
      - NamedFieldPuns
      - OverloadedStrings
      - RankNTypes
      - RecordWildCards
      - TemplateHaskell
    dependencies:
      - base
      - brick
      - containers
      - labyrinth
      - hspec
      - hspec-discover
      - microlens
      - QuickCheck
